<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="<?= assets('styles/app.css') ?>" type="text/css" />
</head>
<body>
    <header id="main_header">
        <div class="logo">
            <a href="<?= routePath('home') ?>">
                <i class="bi bi-joystick"></i> VGL
            </a>
        </div>
        <nav>
            <a href="<?= routePath('games') ?>">Games</a>
            
            <?php if( Services\AuthService::getAuthUser() ) : ?>
            
                <a href="<?= routePath('profile') ?>">Profile</a>
                <a href="<?= routePath('logout') ?>">Logout</a>
                
            <?php endif; ?>
        </nav>
    </header>
    
    <?php include_once './views/' . $view; ?>
    
    <footer id="main_footer">
        <aside>
            <i class="bi bi-c-circle"></i> 2024 - Matthieu Fergola
        </aside>
    </footer>
    
    <?php if( [] !== $flashbag = Core\FlashBag::get() ) : ?>
    
        <div id="flashbag" class="msg-<?= $flashbag['type'] ?>">
            <p>
                <?= $flashbag['message'] ?>
            </p>
        </div>
    
    <?php endif; ?>
    
    <script type="text/javascript" src="<?= assets('js/app.js') ?>"></script>
</body>
</html>